all doc class loading shouldn't fail if the doc can't resolve the class (this doesn't have to be a ClassNotFound but can also be a NoClassDefFoundError)