null check, fix for:
java.lang.NullPointerException: Cannot invoke
"String.contains(java.lang.CharSequence)" because the return value of
"com.servoy.j2db.documentation.IParameter.getDescription()" is null
	at com.servoy.eclipse.debug.script.TypeCreator.getDoc(TypeCreator.java:2717)
	at com.servoy.eclipse.debug.script.TypeCreator.fill(TypeCreator.java:1968)
	at com.servoy.eclipse.debug.script.TypeCreator.createType(TypeCreator.java:1761)
	at com.servoy.eclipse.debug.script.TypeCreator.createClassType(TypeCreator.java:1361)
	at com.servoy.eclipse.debug.script.TypeCreator.createType(TypeCreator.java:696)
	at org.eclipse.dltk.javascript.typeinfo.TypeCache.getType(TypeCache.java:204)