add back commons-lang3_*.jar because of j ava.lang.NoClassDefFoundError: org/apache/commons/lang3/StringEscapeUtils 	at com.servoy.j2db.server.ngclient.template.FormLayoutStructureGenerator.generateLayoutContainer(FormLayoutStructureGenerator.java:179) ~[servoy_ngclient_8.4.0.3400_b1.jar:?] 	at com.servoy.j2db.server.ngclient.template.FormLayoutGenerator.generateFormComponent(FormLayoutGenerator.java:91) ~[servoy_ngclient_8.4.0.3400_b1.jar:?]