extra null checks for:
java.lang.NullPointerException: Cannot invoke
"java.lang.Class.isAssignableFrom(java.lang.Class)" because "cls" is
null
 at com.servoy.eclipse.debug.script.JavaRuntimeType.isAssignableFrom(JavaRuntimeType.java:75)
 at org.eclipse.dltk.internal.javascript.validation.TypeInfoValidator$ValidationVisitor.testArgumentType(TypeInfoValidator.java:1571)