null check for
ava.lang.NullPointerException: Cannot invoke "String.length()" because
"current" is null
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.match(TextFilter.java:466)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.match(TextFilter.java:407)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.matchInList(TextFilter.java:155)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.filterNodeSubtree(TextFilter.java:111)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.filterNodeChildren(TextFilter.java:92)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.filterNodeSubtree(TextFilter.java:128)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.filterNodeChildren(TextFilter.java:92)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.filterNodeSubtree(TextFilter.java:128)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.filterNodeChildren(TextFilter.java:92)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.filter(TextFilter.java:60)
	at com.servoy.eclipse.ui.views.solutionexplorer.SolutionExplorerView.filterTree(SolutionExplorerView.java:3177)
	at com.servoy.eclipse.ui.views.solutionexplorer.SolutionExplorerView.filter(SolutionExplorerView.java:3153)