SVY-19967 NPE when filtering in solex
null check added

java.lang.NullPointerException: Cannot invoke "String.length()" because
"text" is null
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.match(TextFilter.java:407)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.matchInList(TextFilter.java:155)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.filterNodeSubtree(TextFilter.java:111)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.filterNodeChildren(TextFilter.java:92)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.filterNodeSubtree(TextFilter.java:128)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.filterNodeChildren(TextFilter.java:92)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.filterNodeSubtree(TextFilter.java:128)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.filterNodeChildren(TextFilter.java:92)
	at com.servoy.eclipse.ui.views.solutionexplorer.TextFilter.filter(TextFilter.java:60)
	at com.servoy.eclipse.ui.views.solutionexplorer.SolutionExplorerView.filterTree(SolutionExplorerView.java:3042)
	at com.servoy.eclipse.ui.views.solutionexplorer.SolutionExplorerView.filter(SolutionExplorerView.java:3018)
	at com.servoy.eclipse.ui.util.FilterDelayJob.run(FilterDelayJob.java:80)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)